### ISSUE TITLE
Wrong dependencies in version 6.0.216

### ISSUE THREAD

**Issue by drvic10k** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#44]
In version 6.0.216 you are referencing old version of Abstractions (6.0.190)

![image](https://user-images.githubusercontent.com/3754571/214497030-35d8fb2a-4792-451e-af4b-748f7bdfec77.png)

**Comment by RalfHeitmann** [comment]
I just checked the dependencies of the ADS Packages. I don't see any wrong dependency there. Which package shows the problem?

![image](https://user-images.githubusercontent.com/4687980/215988307-f939f0d6-fd4e-4f3e-b828-b86350e5233a.png)
![image](https://user-images.githubusercontent.com/4687980/215988593-93fe6a87-2563-4fd5-889d-48d2037a3aff.png)

Eventually you have a problem with your local nuget package cache. You could try to clean it with nuget CLI commands.

**Comment by drvic10k** [comment]
it's not visible on the package, it is a runtime exception

**Comment by RalfHeitmann** [comment]
Sure, but I expect that within your project a wrong version of the dll is located on the disk, because it is not properly updated by nuget, or because your application build is not renewing the dll from the correct package properly (these are common problems in VisualStudio that bite from time to time).
The runtime simply loads the Assembly it finds in its search path because different Nuget package versions have all the same AssemblyVersion.
You could check the location where the wrong Dll is loaded from in the Vs-Debugger (Modules View) and check that version.


So please ensure:

- remove all TwinCAT.Ads*.dll files from bin and obj folders (or delete these folders) within your VS-Solution
- If that doesn't help delete Nuget package caches and install the Nuget Dependencies again.

Because the package dependencies seem to be correct, it must be an issue in updating/copying the package/dlls on your system. Or picking the wrong dll from an unexpected location during runtime.

**Comment by drvic10k** [comment]
the problem was with an old version of one of our own nuget packages having a dependency on 6.0.190

thanks for pointing me to the solution
